### ISSUE TITLE
Create documentation page about how to set and access configuration values

### ISSUE THREAD

**Issue by erikaheidi** [minicli/docs#7]
Create a documentation page with detailed information on how to set up configuration values and access them from the app container. Include orientation / suggestions on how to extend with config file and ENV vars.

**Comment by erikaheidi** [comment]
@jonathanbossenger sure, it's all yours :D

**Comment by jonathanbossenger** [comment]
Thanks :) Will install and figure it out next week.

**Comment by jonathanbossenger** [comment]
Whoops, this one fell through the cracks. Going to try and pick it up in the coming weeks.
